#ifndef PROMPTS_H
#define PROMPTS_H

#define P_UNIT_OK "UNIT OK"
#define P_UNIT_FAILED "UNIT FAILED"
#define P_CHANGE_BATT "CHANGE BATTERIES"
#define P_STAY_CALM "STAY CALM"
#define P_CHECK_RESP "CHECK RESPONSIVENESS"
#define P_CALL_HELP "CALL FOR HELP"
#define P_PLUG "PLUG IN CABLE"
#define P_ATTACH "ATTACH DEFIB PADS TO PATIENT'S BARE CHEST"
#define P_CHECK_ELEC "CHECK ELECTRODE PADS"
#define P_PAD_ADULT "ADULT PADS"
#define P_PAD_CHILD "CHILD PADS"
#define P_ANALYZING "DON'T TOUCH PATIENT, ANALYZING"
#define P_SHOCKABLE "SHOCK ADVISED"
#define P_NOTSHOCKABLE "NO SHOCK ADVISED"
// #define P_ARTIFACT "ANALYSIS HALTED. KEEP PATIENT STILL" - CUT THIS
#define P_CLEAR "DON'T TOUCH PATIENT. PRESS FLASHING SHOCK BUTTON"
#define P_RELEASE "RELEASE SHOCK BUTTON"
#define P_DELIVERED "SHOCK DELIVERED"
#define P_CPR_START "START CPR"
#define P_CPR_CONT "CONTINUE CPR"
#define P_CPR_HARDER "PUSH HARDER"
#define P_CPR_GOOD "GOOD COMPRESSIONS"
#define P_CPR_STOP "STOP CPR"
#define P_BLANK ""

#define P_GOOD_SPEED "CPR: GOOD COMPRESSION RATE"
#define P_SLIGHTLY_FASTER "CPR: GO A LITTLE FASTER"
#define P_FASTER "CPR: GO FASTER"


#endif // PROMPTS_H
